"""empty message

Revision ID: 1658ac79433
Revises: 4dbb51f1f7
Create Date: 2015-06-10 18:57:07.330232

"""

# revision identifiers, used by Alembic.
revision = '1658ac79433'
down_revision = '4dbb51f1f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_offer_id_country_code_uc', 'offer_countries', ['offer_id', 'country_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_offer_id_country_code_uc', 'offer_countries', type_='unique')
    ### end Alembic commands ###
