"""empty message

Revision ID: 438901b28b4
Revises: c0edce3125
Create Date: 2015-06-30 16:58:03.026383

"""

# revision identifiers, used by Alembic.
revision = '438901b28b4'
down_revision = 'c0edce3125'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_idx_user_login_unique_', 'user', ['login'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_idx_user_login_unique_', 'user', type_='unique')
    ### end Alembic commands ###
