"""add column offer created

Revision ID: 964ed8d036
Revises: 520c4b68d3b
Create Date: 2015-06-18 14:58:04.349197

"""

# revision identifiers, used by Alembic.
revision = '964ed8d036'
down_revision = '520c4b68d3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'created')
    ### end Alembic commands ###
