"""create model offer payout

Revision ID: 520c4b68d3b
Revises: 27a2c0d185c
Create Date: 2015-06-11 19:31:52.040450

"""

# revision identifiers, used by Alembic.
revision = '520c4b68d3b'
down_revision = '27a2c0d185c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout', sa.Float(precision=2), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_payout')
    ### end Alembic commands ###
