"""index on offerevent.name

Revision ID: 204f620bda
Revises: 964ed8d036
Create Date: 2015-06-18 19:04:30.777126

"""

# revision identifiers, used by Alembic.
revision = '204f620bda'
down_revision = '964ed8d036'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_offer_event_name'), 'offer_event', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_event_name'), table_name='offer_event')
    ### end Alembic commands ###
