"""add user fields

Revision ID: c0edce3125
Revises: 19b61156780
Create Date: 2015-06-29 19:54:44.757137

"""

# revision identifiers, used by Alembic.
revision = 'c0edce3125'
down_revision = '19b61156780'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    # op.create_unique_constraint(None, 'user', ['login'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password')
    op.drop_column('user', 'login')
    ### end Alembic commands ###
