"""add column network.tracker

Revision ID: 250c016b270
Revises: 438901b28b4
Create Date: 2015-06-30 17:19:40.025760

"""

# revision identifiers, used by Alembic.
revision = '250c016b270'
down_revision = '438901b28b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network', sa.Column('tracker', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network', 'tracker')
    ### end Alembic commands ###
