"""app_id and platform are not nullable

Revision ID: 27a2c0d185c
Revises: 24d560ccd3e
Create Date: 2015-06-11 17:27:07.744188

"""

# revision identifiers, used by Alembic.
revision = '27a2c0d185c'
down_revision = '24d560ccd3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app', 'app_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('app', 'platform_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app', 'platform_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('app', 'app_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###
