"""empty message

Revision ID: 3a85cbe62ce
Revises: 52fbd9be487
Create Date: 2015-06-08 20:44:59.870553

"""

# revision identifiers, used by Alembic.
revision = '3a85cbe62ce'
down_revision = '52fbd9be487'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_event')
    ### end Alembic commands ###
