"""empty message

Revision ID: 4742f643184
Revises: dfbbfa65e7
Create Date: 2015-06-09 16:22:17.237754

"""

# revision identifiers, used by Alembic.
revision = '4742f643184'
down_revision = 'dfbbfa65e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('remote_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'remote_id')
    ### end Alembic commands ###
