"""empty message

Revision ID: 4dbb51f1f7
Revises: ad14b2ef67
Create Date: 2015-06-09 18:55:39.755606

"""

# revision identifiers, used by Alembic.
revision = '4dbb51f1f7'
down_revision = 'ad14b2ef67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_countries',
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['country.code'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], )
    )
    op.create_index(op.f('ix_offer_countries_country_code'), 'offer_countries', ['country_code'], unique=False)
    op.create_index(op.f('ix_offer_countries_offer_id'), 'offer_countries', ['offer_id'], unique=False)
    op.alter_column('offer', 'payout',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'payout',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_offer_countries_offer_id'), table_name='offer_countries')
    op.drop_index(op.f('ix_offer_countries_country_code'), table_name='offer_countries')
    op.drop_table('offer_countries')
    ### end Alembic commands ###
