"""empty message

Revision ID: 5223fed24de
Revises: 4742f643184
Create Date: 2015-06-09 16:43:49.587558

"""

# revision identifiers, used by Alembic.
revision = '5223fed24de'
down_revision = '4742f643184'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_remote_id_network_id_uc', 'offer', ['remote_id', 'network_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_remote_id_network_id_uc', 'offer', type_='unique')
    ### end Alembic commands ###
