"""empty message

Revision ID: 5443bd4eb59
Revises: 5223fed24de
Create Date: 2015-06-09 16:47:16.789630

"""

# revision identifiers, used by Alembic.
revision = '5443bd4eb59'
down_revision = '5223fed24de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
