"""empty message

Revision ID: 5a17fafba7f
Revises: 86d8f271f6
Create Date: 2015-06-09 16:56:28.135058

"""

# revision identifiers, used by Alembic.
revision = '5a17fafba7f'
down_revision = '86d8f271f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
