"""empty message

Revision ID: 86d8f271f6
Revises: 5443bd4eb59
Create Date: 2015-06-09 16:48:00.933672

"""

# revision identifiers, used by Alembic.
revision = '86d8f271f6'
down_revision = '5443bd4eb59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
