"""empty message

Revision ID: ad14b2ef67
Revises: 63455e0403
Create Date: 2015-06-09 17:51:28.720811

"""

# revision identifiers, used by Alembic.
revision = 'ad14b2ef67'
down_revision = '63455e0403'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.alter_column('offer', 'payout',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'payout',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_table('country')
    ### end Alembic commands ###
